name: Ensure pull requests obey gofmt
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**.go'
jobs:
  run-go-fmt:
    name: Run Go Fmt
    uses: ./.github/workflows/gofmt-check-workflow.yml
